[intermediate1]
private = file:///cfssl/runtime/intermediate/intermediate1-key.pem
certificate = /cfssl/runtime/intermediate/intermediate1.pem
config = /cfssl/config/intermediate-config.json
ca = /cfssl/runtime/ca/ca.pem

[intermediate2]
private = file:///cfssl/runtime/intermediate/intermediate2-key.pem
certificate = /cfssl/runtime/intermediate/intermediate2.pem
config = /cfssl/config/intermediate-config.json
ca = /cfssl/runtime/ca/ca.pem
