apiVersion: v1
kind: Namespace
metadata:
  name: simple-cfssl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-cfssl
  namespace: simple-cfssl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-cfssl
  template:
    metadata:
      labels:
        app: simple-cfssl
    spec:
      containers:
        - name: simple-cfssl
          image: simple-cfssl:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: simple-cfssl
spec:
  selector:
    app: simple-cfssl
  type: NodePort
  ports:
    - protocol: TCP
      port: 30888
      targetPort: 8888
      nodePort: 30888
