# permissions to approve all cfssl-issuer.wikimedia.org requests
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-controller-approve:cfssl-issuer.wikimedia.org
rules:
- apiGroups:
  - cert-manager.io
  resources:
  - signers
  verbs:
  - approve
  resourceNames:
  - issuers.cfssl-issuer.wikimedia.org/*
  - clusterissuers.cfssl-issuer.wikimedia.org/*
