# bind the cert-manager internal approver to approve
# cfssl-issuer.wikimedia.org CertificateRequests
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-controller-approve:cfssl-issuer.wikimedia.org
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-controller-approve:cfssl-issuer.wikimedia.org
subjects:
- kind: ServiceAccount
  name: cert-manager
  namespace: cert-manager
