apiVersion: cfssl-issuer.wikimedia.org/v1alpha1
kind: ClusterIssuer
metadata:
  name: clusterissuer-sample
spec:
  authSecretName: "clusterissuer-sample-credentials"
  url: "http://sample-signer.example.com/api/v1"
