apiVersion: cfssl-issuer.wikimedia.org/v1alpha1
kind: ClusterIssuer
metadata:
  name: clusterissuer-sample
spec:
  authSecretName: "clusterissuer-sample-credentials"
  url: "https://api.simple-cfssl.svc.cluster.local:30888,https://dead.end.local"
  label: "intermediate1"
